%fama_macbeth(general.mensual, Lead_Ri_m_Rf, SIZE, t6.size)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, BM, t6.bm)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, LAGGED_RI, t6.lagged_ri)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, BETA_1M, t6.beta_1m)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, BETA_12M, t6.beta_12m)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, ERRORS_1M, t6.errors_1m)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, SIZE BM LAGGED_RI BETA_1M ERRORS_1M, t6.many)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, SIZE BM LAGGED_RI BETA_1M ERRORS_1M PRECIO, t6.many_price)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, SIZE BM LAGGED_RI BETA_1M ERRORS_1M VOLUMEN, t6.many_volumen)
%fama_macbeth(general.mensual, Lead_Ri_m_Rf, SIZE BM LAGGED_RI BETA_1M ERRORS_1M BA_SPREAD, t6.many_baSpread)
